# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pacote.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pacote.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('Z#github.com/dadosjusbr/proto/csv;csv'),
  serialized_pb=_b('\n\x0cpacote.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x01\n\x13ResultadoColeta_CSV\x12\x1b\n\x06\x63oleta\x18\x01 \x01(\x0b\x32\x0b.Coleta_CSV\x12\'\n\x0cremuneracoes\x18\x02 \x01(\x0b\x32\x11.Remuneracoes_CSV\x12$\n\x05\x66olha\x18\x03 \x01(\x0b\x32\x15.FolhaDePagamento_CSV\"\xcb\x01\n\nColeta_CSV\x12\x14\n\x0c\x63have_coleta\x18\x01 \x01(\t\x12\r\n\x05orgao\x18\x02 \x01(\t\x12\x0b\n\x03mes\x18\x03 \x01(\x05\x12\x0b\n\x03\x61no\x18\x04 \x01(\x05\x12\x34\n\x10timestamp_coleta\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1b\n\x13repositorio_coletor\x18\x06 \x01(\t\x12\x16\n\x0eversao_coletor\x18\x07 \x01(\t\x12\x13\n\x0b\x64ir_coletor\x18\x08 \x01(\t\"@\n\x14\x46olhaDePagamento_CSV\x12(\n\rcontra_cheque\x18\x01 \x03(\x0b\x32\x11.ContraCheque_CSV\"\xe2\x01\n\x10\x43ontraCheque_CSV\x12\x18\n\x10id_contra_cheque\x18\x01 \x01(\t\x12\x14\n\x0c\x63have_coleta\x18\x02 \x01(\t\x12\x0c\n\x04nome\x18\x03 \x01(\t\x12\x11\n\tmatricula\x18\x04 \x01(\t\x12\x0e\n\x06\x66uncao\x18\x05 \x01(\t\x12\x16\n\x0elocal_trabalho\x18\x06 \x01(\t\x12$\n\x04tipo\x18\x07 \x01(\x0e\x32\x16.ContraCheque_CSV.Tipo\x12\r\n\x05\x61tivo\x18\x08 \x01(\x08\" \n\x04Tipo\x12\n\n\x06MEMBRO\x10\x00\x12\x0c\n\x08SERVIDOR\x10\x01\"9\n\x10Remuneracoes_CSV\x12%\n\x0bremuneracao\x18\x01 \x03(\x0b\x32\x10.Remuneracao_CSV\"\xb8\x01\n\x0fRemuneracao_CSV\x12\x18\n\x10id_contra_cheque\x18\x01 \x01(\t\x12\x14\n\x0c\x63have_coleta\x18\x02 \x01(\t\x12+\n\x08natureza\x18\x03 \x01(\x0e\x32\x19.Remuneracao_CSV.Natureza\x12\x11\n\tcategoria\x18\x04 \x01(\t\x12\x0c\n\x04item\x18\x05 \x01(\t\x12\r\n\x05valor\x18\x06 \x01(\x01\"\x18\n\x08Natureza\x12\x05\n\x01R\x10\x00\x12\x05\n\x01\x44\x10\x01\x42%Z#github.com/dadosjusbr/proto/csv;csvb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_CONTRACHEQUE_CSV_TIPO = _descriptor.EnumDescriptor(
  name='Tipo',
  full_name='ContraCheque_CSV.Tipo',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MEMBRO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVIDOR', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=648,
  serialized_end=680,
)
_sym_db.RegisterEnumDescriptor(_CONTRACHEQUE_CSV_TIPO)

_REMUNERACAO_CSV_NATUREZA = _descriptor.EnumDescriptor(
  name='Natureza',
  full_name='Remuneracao_CSV.Natureza',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='R', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=902,
  serialized_end=926,
)
_sym_db.RegisterEnumDescriptor(_REMUNERACAO_CSV_NATUREZA)


_RESULTADOCOLETA_CSV = _descriptor.Descriptor(
  name='ResultadoColeta_CSV',
  full_name='ResultadoColeta_CSV',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coleta', full_name='ResultadoColeta_CSV.coleta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remuneracoes', full_name='ResultadoColeta_CSV.remuneracoes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='folha', full_name='ResultadoColeta_CSV.folha', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=179,
)


_COLETA_CSV = _descriptor.Descriptor(
  name='Coleta_CSV',
  full_name='Coleta_CSV',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave_coleta', full_name='Coleta_CSV.chave_coleta', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orgao', full_name='Coleta_CSV.orgao', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mes', full_name='Coleta_CSV.mes', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ano', full_name='Coleta_CSV.ano', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_coleta', full_name='Coleta_CSV.timestamp_coleta', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repositorio_coletor', full_name='Coleta_CSV.repositorio_coletor', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versao_coletor', full_name='Coleta_CSV.versao_coletor', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dir_coletor', full_name='Coleta_CSV.dir_coletor', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=385,
)


_FOLHADEPAGAMENTO_CSV = _descriptor.Descriptor(
  name='FolhaDePagamento_CSV',
  full_name='FolhaDePagamento_CSV',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contra_cheque', full_name='FolhaDePagamento_CSV.contra_cheque', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=451,
)


_CONTRACHEQUE_CSV = _descriptor.Descriptor(
  name='ContraCheque_CSV',
  full_name='ContraCheque_CSV',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_contra_cheque', full_name='ContraCheque_CSV.id_contra_cheque', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chave_coleta', full_name='ContraCheque_CSV.chave_coleta', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nome', full_name='ContraCheque_CSV.nome', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matricula', full_name='ContraCheque_CSV.matricula', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='funcao', full_name='ContraCheque_CSV.funcao', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='local_trabalho', full_name='ContraCheque_CSV.local_trabalho', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tipo', full_name='ContraCheque_CSV.tipo', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ativo', full_name='ContraCheque_CSV.ativo', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTRACHEQUE_CSV_TIPO,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=680,
)


_REMUNERACOES_CSV = _descriptor.Descriptor(
  name='Remuneracoes_CSV',
  full_name='Remuneracoes_CSV',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='remuneracao', full_name='Remuneracoes_CSV.remuneracao', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=682,
  serialized_end=739,
)


_REMUNERACAO_CSV = _descriptor.Descriptor(
  name='Remuneracao_CSV',
  full_name='Remuneracao_CSV',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_contra_cheque', full_name='Remuneracao_CSV.id_contra_cheque', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chave_coleta', full_name='Remuneracao_CSV.chave_coleta', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='natureza', full_name='Remuneracao_CSV.natureza', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='categoria', full_name='Remuneracao_CSV.categoria', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item', full_name='Remuneracao_CSV.item', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valor', full_name='Remuneracao_CSV.valor', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REMUNERACAO_CSV_NATUREZA,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=742,
  serialized_end=926,
)

_RESULTADOCOLETA_CSV.fields_by_name['coleta'].message_type = _COLETA_CSV
_RESULTADOCOLETA_CSV.fields_by_name['remuneracoes'].message_type = _REMUNERACOES_CSV
_RESULTADOCOLETA_CSV.fields_by_name['folha'].message_type = _FOLHADEPAGAMENTO_CSV
_COLETA_CSV.fields_by_name['timestamp_coleta'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_FOLHADEPAGAMENTO_CSV.fields_by_name['contra_cheque'].message_type = _CONTRACHEQUE_CSV
_CONTRACHEQUE_CSV.fields_by_name['tipo'].enum_type = _CONTRACHEQUE_CSV_TIPO
_CONTRACHEQUE_CSV_TIPO.containing_type = _CONTRACHEQUE_CSV
_REMUNERACOES_CSV.fields_by_name['remuneracao'].message_type = _REMUNERACAO_CSV
_REMUNERACAO_CSV.fields_by_name['natureza'].enum_type = _REMUNERACAO_CSV_NATUREZA
_REMUNERACAO_CSV_NATUREZA.containing_type = _REMUNERACAO_CSV
DESCRIPTOR.message_types_by_name['ResultadoColeta_CSV'] = _RESULTADOCOLETA_CSV
DESCRIPTOR.message_types_by_name['Coleta_CSV'] = _COLETA_CSV
DESCRIPTOR.message_types_by_name['FolhaDePagamento_CSV'] = _FOLHADEPAGAMENTO_CSV
DESCRIPTOR.message_types_by_name['ContraCheque_CSV'] = _CONTRACHEQUE_CSV
DESCRIPTOR.message_types_by_name['Remuneracoes_CSV'] = _REMUNERACOES_CSV
DESCRIPTOR.message_types_by_name['Remuneracao_CSV'] = _REMUNERACAO_CSV
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResultadoColeta_CSV = _reflection.GeneratedProtocolMessageType('ResultadoColeta_CSV', (_message.Message,), dict(
  DESCRIPTOR = _RESULTADOCOLETA_CSV,
  __module__ = 'pacote_pb2'
  # @@protoc_insertion_point(class_scope:ResultadoColeta_CSV)
  ))
_sym_db.RegisterMessage(ResultadoColeta_CSV)

Coleta_CSV = _reflection.GeneratedProtocolMessageType('Coleta_CSV', (_message.Message,), dict(
  DESCRIPTOR = _COLETA_CSV,
  __module__ = 'pacote_pb2'
  # @@protoc_insertion_point(class_scope:Coleta_CSV)
  ))
_sym_db.RegisterMessage(Coleta_CSV)

FolhaDePagamento_CSV = _reflection.GeneratedProtocolMessageType('FolhaDePagamento_CSV', (_message.Message,), dict(
  DESCRIPTOR = _FOLHADEPAGAMENTO_CSV,
  __module__ = 'pacote_pb2'
  # @@protoc_insertion_point(class_scope:FolhaDePagamento_CSV)
  ))
_sym_db.RegisterMessage(FolhaDePagamento_CSV)

ContraCheque_CSV = _reflection.GeneratedProtocolMessageType('ContraCheque_CSV', (_message.Message,), dict(
  DESCRIPTOR = _CONTRACHEQUE_CSV,
  __module__ = 'pacote_pb2'
  # @@protoc_insertion_point(class_scope:ContraCheque_CSV)
  ))
_sym_db.RegisterMessage(ContraCheque_CSV)

Remuneracoes_CSV = _reflection.GeneratedProtocolMessageType('Remuneracoes_CSV', (_message.Message,), dict(
  DESCRIPTOR = _REMUNERACOES_CSV,
  __module__ = 'pacote_pb2'
  # @@protoc_insertion_point(class_scope:Remuneracoes_CSV)
  ))
_sym_db.RegisterMessage(Remuneracoes_CSV)

Remuneracao_CSV = _reflection.GeneratedProtocolMessageType('Remuneracao_CSV', (_message.Message,), dict(
  DESCRIPTOR = _REMUNERACAO_CSV,
  __module__ = 'pacote_pb2'
  # @@protoc_insertion_point(class_scope:Remuneracao_CSV)
  ))
_sym_db.RegisterMessage(Remuneracao_CSV)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
