// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: pacote.proto

package csv

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContraCheque_CSV_Tipo int32

const (
	ContraCheque_CSV_MEMBRO   ContraCheque_CSV_Tipo = 0
	ContraCheque_CSV_SERVIDOR ContraCheque_CSV_Tipo = 1
)

// Enum value maps for ContraCheque_CSV_Tipo.
var (
	ContraCheque_CSV_Tipo_name = map[int32]string{
		0: "MEMBRO",
		1: "SERVIDOR",
	}
	ContraCheque_CSV_Tipo_value = map[string]int32{
		"MEMBRO":   0,
		"SERVIDOR": 1,
	}
)

func (x ContraCheque_CSV_Tipo) Enum() *ContraCheque_CSV_Tipo {
	p := new(ContraCheque_CSV_Tipo)
	*p = x
	return p
}

func (x ContraCheque_CSV_Tipo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContraCheque_CSV_Tipo) Descriptor() protoreflect.EnumDescriptor {
	return file_pacote_proto_enumTypes[0].Descriptor()
}

func (ContraCheque_CSV_Tipo) Type() protoreflect.EnumType {
	return &file_pacote_proto_enumTypes[0]
}

func (x ContraCheque_CSV_Tipo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContraCheque_CSV_Tipo.Descriptor instead.
func (ContraCheque_CSV_Tipo) EnumDescriptor() ([]byte, []int) {
	return file_pacote_proto_rawDescGZIP(), []int{3, 0}
}

type Remuneracao_CSV_Natureza int32

const (
	Remuneracao_CSV_R Remuneracao_CSV_Natureza = 0 //Receita
	Remuneracao_CSV_D Remuneracao_CSV_Natureza = 1 //Despesa
)

// Enum value maps for Remuneracao_CSV_Natureza.
var (
	Remuneracao_CSV_Natureza_name = map[int32]string{
		0: "R",
		1: "D",
	}
	Remuneracao_CSV_Natureza_value = map[string]int32{
		"R": 0,
		"D": 1,
	}
)

func (x Remuneracao_CSV_Natureza) Enum() *Remuneracao_CSV_Natureza {
	p := new(Remuneracao_CSV_Natureza)
	*p = x
	return p
}

func (x Remuneracao_CSV_Natureza) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Remuneracao_CSV_Natureza) Descriptor() protoreflect.EnumDescriptor {
	return file_pacote_proto_enumTypes[1].Descriptor()
}

func (Remuneracao_CSV_Natureza) Type() protoreflect.EnumType {
	return &file_pacote_proto_enumTypes[1]
}

func (x Remuneracao_CSV_Natureza) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Remuneracao_CSV_Natureza.Descriptor instead.
func (Remuneracao_CSV_Natureza) EnumDescriptor() ([]byte, []int) {
	return file_pacote_proto_rawDescGZIP(), []int{5, 0}
}

type Metadados_CSV_FormaDeAcesso int32

const (
	Metadados_CSV_ACESSO_DIRETO               Metadados_CSV_FormaDeAcesso = 0 // Acesso ao dado pode ser diretamente ou via API
	Metadados_CSV_AMIGAVEL_PARA_RASPAGEM      Metadados_CSV_FormaDeAcesso = 1 // Aqui temos URLs determinísticas, tags usadas com semântica bem-definida
	Metadados_CSV_RASPAGEM_DIFICULTADA        Metadados_CSV_FormaDeAcesso = 2 // URLs não determinísticas, tags com semântica difusa (dois componentes com mesmo id)
	Metadados_CSV_NECESSITA_SIMULACAO_USUARIO Metadados_CSV_FormaDeAcesso = 3 // Não dá para fazer raspagem e precisou simular cliques de usuário
)

// Enum value maps for Metadados_CSV_FormaDeAcesso.
var (
	Metadados_CSV_FormaDeAcesso_name = map[int32]string{
		0: "ACESSO_DIRETO",
		1: "AMIGAVEL_PARA_RASPAGEM",
		2: "RASPAGEM_DIFICULTADA",
		3: "NECESSITA_SIMULACAO_USUARIO",
	}
	Metadados_CSV_FormaDeAcesso_value = map[string]int32{
		"ACESSO_DIRETO":               0,
		"AMIGAVEL_PARA_RASPAGEM":      1,
		"RASPAGEM_DIFICULTADA":        2,
		"NECESSITA_SIMULACAO_USUARIO": 3,
	}
)

func (x Metadados_CSV_FormaDeAcesso) Enum() *Metadados_CSV_FormaDeAcesso {
	p := new(Metadados_CSV_FormaDeAcesso)
	*p = x
	return p
}

func (x Metadados_CSV_FormaDeAcesso) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metadados_CSV_FormaDeAcesso) Descriptor() protoreflect.EnumDescriptor {
	return file_pacote_proto_enumTypes[2].Descriptor()
}

func (Metadados_CSV_FormaDeAcesso) Type() protoreflect.EnumType {
	return &file_pacote_proto_enumTypes[2]
}

func (x Metadados_CSV_FormaDeAcesso) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metadados_CSV_FormaDeAcesso.Descriptor instead.
func (Metadados_CSV_FormaDeAcesso) EnumDescriptor() ([]byte, []int) {
	return file_pacote_proto_rawDescGZIP(), []int{6, 0}
}

type Metadados_CSV_Extensao int32

const (
	Metadados_CSV_PDF  Metadados_CSV_Extensao = 0
	Metadados_CSV_ODS  Metadados_CSV_Extensao = 1
	Metadados_CSV_XLS  Metadados_CSV_Extensao = 2
	Metadados_CSV_JSON Metadados_CSV_Extensao = 3
	Metadados_CSV_CSV  Metadados_CSV_Extensao = 4
)

// Enum value maps for Metadados_CSV_Extensao.
var (
	Metadados_CSV_Extensao_name = map[int32]string{
		0: "PDF",
		1: "ODS",
		2: "XLS",
		3: "JSON",
		4: "CSV",
	}
	Metadados_CSV_Extensao_value = map[string]int32{
		"PDF":  0,
		"ODS":  1,
		"XLS":  2,
		"JSON": 3,
		"CSV":  4,
	}
)

func (x Metadados_CSV_Extensao) Enum() *Metadados_CSV_Extensao {
	p := new(Metadados_CSV_Extensao)
	*p = x
	return p
}

func (x Metadados_CSV_Extensao) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metadados_CSV_Extensao) Descriptor() protoreflect.EnumDescriptor {
	return file_pacote_proto_enumTypes[3].Descriptor()
}

func (Metadados_CSV_Extensao) Type() protoreflect.EnumType {
	return &file_pacote_proto_enumTypes[3]
}

func (x Metadados_CSV_Extensao) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metadados_CSV_Extensao.Descriptor instead.
func (Metadados_CSV_Extensao) EnumDescriptor() ([]byte, []int) {
	return file_pacote_proto_rawDescGZIP(), []int{6, 1}
}

type Metadados_CSV_OpcoesDetalhamento int32

const (
	Metadados_CSV_AUSENCIA   Metadados_CSV_OpcoesDetalhamento = 0
	Metadados_CSV_SUMARIZADO Metadados_CSV_OpcoesDetalhamento = 1
	Metadados_CSV_DETALHADO  Metadados_CSV_OpcoesDetalhamento = 2
)

// Enum value maps for Metadados_CSV_OpcoesDetalhamento.
var (
	Metadados_CSV_OpcoesDetalhamento_name = map[int32]string{
		0: "AUSENCIA",
		1: "SUMARIZADO",
		2: "DETALHADO",
	}
	Metadados_CSV_OpcoesDetalhamento_value = map[string]int32{
		"AUSENCIA":   0,
		"SUMARIZADO": 1,
		"DETALHADO":  2,
	}
)

func (x Metadados_CSV_OpcoesDetalhamento) Enum() *Metadados_CSV_OpcoesDetalhamento {
	p := new(Metadados_CSV_OpcoesDetalhamento)
	*p = x
	return p
}

func (x Metadados_CSV_OpcoesDetalhamento) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metadados_CSV_OpcoesDetalhamento) Descriptor() protoreflect.EnumDescriptor {
	return file_pacote_proto_enumTypes[4].Descriptor()
}

func (Metadados_CSV_OpcoesDetalhamento) Type() protoreflect.EnumType {
	return &file_pacote_proto_enumTypes[4]
}

func (x Metadados_CSV_OpcoesDetalhamento) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metadados_CSV_OpcoesDetalhamento.Descriptor instead.
func (Metadados_CSV_OpcoesDetalhamento) EnumDescriptor() ([]byte, []int) {
	return file_pacote_proto_rawDescGZIP(), []int{6, 2}
}

// Estrutura com informações pertencentes a execução da coleta dos dados.
type ResultadoColeta_CSV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coleta       *Coleta_CSV           `protobuf:"bytes,1,opt,name=coleta,proto3" json:"coleta,omitempty"`
	Remuneracoes *Remuneracoes_CSV     `protobuf:"bytes,2,opt,name=remuneracoes,proto3" json:"remuneracoes,omitempty"`
	Folha        *FolhaDePagamento_CSV `protobuf:"bytes,3,opt,name=folha,proto3" json:"folha,omitempty"`
	Metadados    *Metadados_CSV        `protobuf:"bytes,4,opt,name=metadados,proto3" json:"metadados,omitempty"`
}

func (x *ResultadoColeta_CSV) Reset() {
	*x = ResultadoColeta_CSV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pacote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultadoColeta_CSV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoColeta_CSV) ProtoMessage() {}

func (x *ResultadoColeta_CSV) ProtoReflect() protoreflect.Message {
	mi := &file_pacote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoColeta_CSV.ProtoReflect.Descriptor instead.
func (*ResultadoColeta_CSV) Descriptor() ([]byte, []int) {
	return file_pacote_proto_rawDescGZIP(), []int{0}
}

func (x *ResultadoColeta_CSV) GetColeta() *Coleta_CSV {
	if x != nil {
		return x.Coleta
	}
	return nil
}

func (x *ResultadoColeta_CSV) GetRemuneracoes() *Remuneracoes_CSV {
	if x != nil {
		return x.Remuneracoes
	}
	return nil
}

func (x *ResultadoColeta_CSV) GetFolha() *FolhaDePagamento_CSV {
	if x != nil {
		return x.Folha
	}
	return nil
}

func (x *ResultadoColeta_CSV) GetMetadados() *Metadados_CSV {
	if x != nil {
		return x.Metadados
	}
	return nil
}

// Estrutura com informações pertencentes a coleta dos dados referentes a um órgão-mes-ano
type Coleta_CSV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChaveColeta        string               `protobuf:"bytes,1,opt,name=chave_coleta,json=chaveColeta,proto3" json:"chave_coleta,omitempty"`
	Orgao              string               `protobuf:"bytes,2,opt,name=orgao,proto3" json:"orgao,omitempty"`
	Mes                int32                `protobuf:"varint,3,opt,name=mes,proto3" json:"mes,omitempty"`
	Ano                int32                `protobuf:"varint,4,opt,name=ano,proto3" json:"ano,omitempty"`
	TimestampColeta    *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp_coleta,json=timestampColeta,proto3" json:"timestamp_coleta,omitempty"`
	RepositorioColetor string               `protobuf:"bytes,6,opt,name=repositorio_coletor,json=repositorioColetor,proto3" json:"repositorio_coletor,omitempty"`
	VersaoColetor      string               `protobuf:"bytes,7,opt,name=versao_coletor,json=versaoColetor,proto3" json:"versao_coletor,omitempty"`
	DirColetor         string               `protobuf:"bytes,8,opt,name=dir_coletor,json=dirColetor,proto3" json:"dir_coletor,omitempty"`
}

func (x *Coleta_CSV) Reset() {
	*x = Coleta_CSV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pacote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coleta_CSV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coleta_CSV) ProtoMessage() {}

func (x *Coleta_CSV) ProtoReflect() protoreflect.Message {
	mi := &file_pacote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coleta_CSV.ProtoReflect.Descriptor instead.
func (*Coleta_CSV) Descriptor() ([]byte, []int) {
	return file_pacote_proto_rawDescGZIP(), []int{1}
}

func (x *Coleta_CSV) GetChaveColeta() string {
	if x != nil {
		return x.ChaveColeta
	}
	return ""
}

func (x *Coleta_CSV) GetOrgao() string {
	if x != nil {
		return x.Orgao
	}
	return ""
}

func (x *Coleta_CSV) GetMes() int32 {
	if x != nil {
		return x.Mes
	}
	return 0
}

func (x *Coleta_CSV) GetAno() int32 {
	if x != nil {
		return x.Ano
	}
	return 0
}

func (x *Coleta_CSV) GetTimestampColeta() *timestamp.Timestamp {
	if x != nil {
		return x.TimestampColeta
	}
	return nil
}

func (x *Coleta_CSV) GetRepositorioColetor() string {
	if x != nil {
		return x.RepositorioColetor
	}
	return ""
}

func (x *Coleta_CSV) GetVersaoColetor() string {
	if x != nil {
		return x.VersaoColetor
	}
	return ""
}

func (x *Coleta_CSV) GetDirColetor() string {
	if x != nil {
		return x.DirColetor
	}
	return ""
}

// Estrutura que faz referência a uma lista de contra-cheques
type FolhaDePagamento_CSV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContraCheque []*ContraCheque_CSV `protobuf:"bytes,1,rep,name=contra_cheque,json=contraCheque,proto3" json:"contra_cheque,omitempty"`
}

func (x *FolhaDePagamento_CSV) Reset() {
	*x = FolhaDePagamento_CSV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pacote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FolhaDePagamento_CSV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolhaDePagamento_CSV) ProtoMessage() {}

func (x *FolhaDePagamento_CSV) ProtoReflect() protoreflect.Message {
	mi := &file_pacote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolhaDePagamento_CSV.ProtoReflect.Descriptor instead.
func (*FolhaDePagamento_CSV) Descriptor() ([]byte, []int) {
	return file_pacote_proto_rawDescGZIP(), []int{2}
}

func (x *FolhaDePagamento_CSV) GetContraCheque() []*ContraCheque_CSV {
	if x != nil {
		return x.ContraCheque
	}
	return nil
}

// Estrutura que faz referência a uma linha de contra-cheque em um órgão-mes-ano
type ContraCheque_CSV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdContraCheque string                `protobuf:"bytes,1,opt,name=id_contra_cheque,json=idContraCheque,proto3" json:"id_contra_cheque,omitempty"`
	ChaveColeta    string                `protobuf:"bytes,2,opt,name=chave_coleta,json=chaveColeta,proto3" json:"chave_coleta,omitempty"`
	Nome           string                `protobuf:"bytes,3,opt,name=nome,proto3" json:"nome,omitempty"`
	Matricula      string                `protobuf:"bytes,4,opt,name=matricula,proto3" json:"matricula,omitempty"`
	Funcao         string                `protobuf:"bytes,5,opt,name=funcao,proto3" json:"funcao,omitempty"`
	LocalTrabalho  string                `protobuf:"bytes,6,opt,name=local_trabalho,json=localTrabalho,proto3" json:"local_trabalho,omitempty"`
	Tipo           ContraCheque_CSV_Tipo `protobuf:"varint,7,opt,name=tipo,proto3,enum=ContraCheque_CSV_Tipo" json:"tipo,omitempty"`
	Ativo          bool                  `protobuf:"varint,8,opt,name=ativo,proto3" json:"ativo,omitempty"`
}

func (x *ContraCheque_CSV) Reset() {
	*x = ContraCheque_CSV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pacote_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContraCheque_CSV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContraCheque_CSV) ProtoMessage() {}

func (x *ContraCheque_CSV) ProtoReflect() protoreflect.Message {
	mi := &file_pacote_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContraCheque_CSV.ProtoReflect.Descriptor instead.
func (*ContraCheque_CSV) Descriptor() ([]byte, []int) {
	return file_pacote_proto_rawDescGZIP(), []int{3}
}

func (x *ContraCheque_CSV) GetIdContraCheque() string {
	if x != nil {
		return x.IdContraCheque
	}
	return ""
}

func (x *ContraCheque_CSV) GetChaveColeta() string {
	if x != nil {
		return x.ChaveColeta
	}
	return ""
}

func (x *ContraCheque_CSV) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *ContraCheque_CSV) GetMatricula() string {
	if x != nil {
		return x.Matricula
	}
	return ""
}

func (x *ContraCheque_CSV) GetFuncao() string {
	if x != nil {
		return x.Funcao
	}
	return ""
}

func (x *ContraCheque_CSV) GetLocalTrabalho() string {
	if x != nil {
		return x.LocalTrabalho
	}
	return ""
}

func (x *ContraCheque_CSV) GetTipo() ContraCheque_CSV_Tipo {
	if x != nil {
		return x.Tipo
	}
	return ContraCheque_CSV_MEMBRO
}

func (x *ContraCheque_CSV) GetAtivo() bool {
	if x != nil {
		return x.Ativo
	}
	return false
}

// Estrutura que faz referência a uma lista de Remunerações
type Remuneracoes_CSV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remuneracao []*Remuneracao_CSV `protobuf:"bytes,1,rep,name=remuneracao,proto3" json:"remuneracao,omitempty"`
}

func (x *Remuneracoes_CSV) Reset() {
	*x = Remuneracoes_CSV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pacote_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Remuneracoes_CSV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remuneracoes_CSV) ProtoMessage() {}

func (x *Remuneracoes_CSV) ProtoReflect() protoreflect.Message {
	mi := &file_pacote_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remuneracoes_CSV.ProtoReflect.Descriptor instead.
func (*Remuneracoes_CSV) Descriptor() ([]byte, []int) {
	return file_pacote_proto_rawDescGZIP(), []int{4}
}

func (x *Remuneracoes_CSV) GetRemuneracao() []*Remuneracao_CSV {
	if x != nil {
		return x.Remuneracao
	}
	return nil
}

// Estrutura que faz referência a uma linha de remuneração em um órgão-mes-ano
type Remuneracao_CSV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdContraCheque string                   `protobuf:"bytes,1,opt,name=id_contra_cheque,json=idContraCheque,proto3" json:"id_contra_cheque,omitempty"`
	ChaveColeta    string                   `protobuf:"bytes,2,opt,name=chave_coleta,json=chaveColeta,proto3" json:"chave_coleta,omitempty"`
	Natureza       Remuneracao_CSV_Natureza `protobuf:"varint,3,opt,name=natureza,proto3,enum=Remuneracao_CSV_Natureza" json:"natureza,omitempty"`
	Categoria      string                   `protobuf:"bytes,4,opt,name=categoria,proto3" json:"categoria,omitempty"`
	Item           string                   `protobuf:"bytes,5,opt,name=item,proto3" json:"item,omitempty"`
	Valor          float64                  `protobuf:"fixed64,6,opt,name=valor,proto3" json:"valor,omitempty"`
}

func (x *Remuneracao_CSV) Reset() {
	*x = Remuneracao_CSV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pacote_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Remuneracao_CSV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remuneracao_CSV) ProtoMessage() {}

func (x *Remuneracao_CSV) ProtoReflect() protoreflect.Message {
	mi := &file_pacote_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remuneracao_CSV.ProtoReflect.Descriptor instead.
func (*Remuneracao_CSV) Descriptor() ([]byte, []int) {
	return file_pacote_proto_rawDescGZIP(), []int{5}
}

func (x *Remuneracao_CSV) GetIdContraCheque() string {
	if x != nil {
		return x.IdContraCheque
	}
	return ""
}

func (x *Remuneracao_CSV) GetChaveColeta() string {
	if x != nil {
		return x.ChaveColeta
	}
	return ""
}

func (x *Remuneracao_CSV) GetNatureza() Remuneracao_CSV_Natureza {
	if x != nil {
		return x.Natureza
	}
	return Remuneracao_CSV_R
}

func (x *Remuneracao_CSV) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *Remuneracao_CSV) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *Remuneracao_CSV) GetValor() float64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

// Estrutura que faz referência aos metadadoss utilizados para construção do índice de transparência
type Metadados_CSV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NaoRequerLogin             bool                             `protobuf:"varint,1,opt,name=nao_requer_login,json=naoRequerLogin,proto3" json:"nao_requer_login,omitempty"`                                                                            // É necessário login para coleta dos dados?
	NaoRequerCaptcha           bool                             `protobuf:"varint,2,opt,name=nao_requer_captcha,json=naoRequerCaptcha,proto3" json:"nao_requer_captcha,omitempty"`                                                                      // É necessário captcha para coleta dos dados?
	Acesso                     Metadados_CSV_FormaDeAcesso      `protobuf:"varint,3,opt,name=acesso,proto3,enum=Metadados_CSV_FormaDeAcesso" json:"acesso,omitempty"`                                                                                   // Conseguimos prever/construir uma URL com base no órgão/mês/ano que leve ao download do dado?
	Extensao                   Metadados_CSV_Extensao           `protobuf:"varint,4,opt,name=extensao,proto3,enum=Metadados_CSV_Extensao" json:"extensao,omitempty"`                                                                                    // Extensao do arquivo de dados, ex: CSV, JSON, XLS, etc
	EstritamenteTabular        bool                             `protobuf:"varint,5,opt,name=estritamente_tabular,json=estritamenteTabular,proto3" json:"estritamente_tabular,omitempty"`                                                               // Órgãos que disponibilizam dados limpos (tidy data)
	FormatoConsistente         bool                             `protobuf:"varint,6,opt,name=formato_consistente,json=formatoConsistente,proto3" json:"formato_consistente,omitempty"`                                                                  // Órgão alterou a forma de expor seus dados entre o mês em questão e o mês anterior?
	TemMatricula               bool                             `protobuf:"varint,7,opt,name=tem_matricula,json=temMatricula,proto3" json:"tem_matricula,omitempty"`                                                                                    // Órgão disponibiliza matrícula do servidor?
	TemLotacao                 bool                             `protobuf:"varint,8,opt,name=tem_lotacao,json=temLotacao,proto3" json:"tem_lotacao,omitempty"`                                                                                          // Órgão disponibiliza lotação do servidor?
	TemCargo                   bool                             `protobuf:"varint,9,opt,name=tem_cargo,json=temCargo,proto3" json:"tem_cargo,omitempty"`                                                                                                // Órgão disponibiliza a função do servidor?
	DetalhamentoReceitaBase    Metadados_CSV_OpcoesDetalhamento `protobuf:"varint,10,opt,name=detalhamento_receita_base,json=detalhamentoReceitaBase,proto3,enum=Metadados_CSV_OpcoesDetalhamento" json:"detalhamento_receita_base,omitempty"`          // Contra-cheque
	DetalhamentoOutrasReceitas Metadados_CSV_OpcoesDetalhamento `protobuf:"varint,11,opt,name=detalhamento_outras_receitas,json=detalhamentoOutrasReceitas,proto3,enum=Metadados_CSV_OpcoesDetalhamento" json:"detalhamento_outras_receitas,omitempty"` // Inclui indenizações, direitos eventuais, diárias, etc
	DetalhamentoDescontos      Metadados_CSV_OpcoesDetalhamento `protobuf:"varint,12,opt,name=detalhamento_descontos,json=detalhamentoDescontos,proto3,enum=Metadados_CSV_OpcoesDetalhamento" json:"detalhamento_descontos,omitempty"`                  // Inclui imposto de renda, retenção por teto e contribuição previdenciária
}

func (x *Metadados_CSV) Reset() {
	*x = Metadados_CSV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pacote_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadados_CSV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadados_CSV) ProtoMessage() {}

func (x *Metadados_CSV) ProtoReflect() protoreflect.Message {
	mi := &file_pacote_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadados_CSV.ProtoReflect.Descriptor instead.
func (*Metadados_CSV) Descriptor() ([]byte, []int) {
	return file_pacote_proto_rawDescGZIP(), []int{6}
}

func (x *Metadados_CSV) GetNaoRequerLogin() bool {
	if x != nil {
		return x.NaoRequerLogin
	}
	return false
}

func (x *Metadados_CSV) GetNaoRequerCaptcha() bool {
	if x != nil {
		return x.NaoRequerCaptcha
	}
	return false
}

func (x *Metadados_CSV) GetAcesso() Metadados_CSV_FormaDeAcesso {
	if x != nil {
		return x.Acesso
	}
	return Metadados_CSV_ACESSO_DIRETO
}

func (x *Metadados_CSV) GetExtensao() Metadados_CSV_Extensao {
	if x != nil {
		return x.Extensao
	}
	return Metadados_CSV_PDF
}

func (x *Metadados_CSV) GetEstritamenteTabular() bool {
	if x != nil {
		return x.EstritamenteTabular
	}
	return false
}

func (x *Metadados_CSV) GetFormatoConsistente() bool {
	if x != nil {
		return x.FormatoConsistente
	}
	return false
}

func (x *Metadados_CSV) GetTemMatricula() bool {
	if x != nil {
		return x.TemMatricula
	}
	return false
}

func (x *Metadados_CSV) GetTemLotacao() bool {
	if x != nil {
		return x.TemLotacao
	}
	return false
}

func (x *Metadados_CSV) GetTemCargo() bool {
	if x != nil {
		return x.TemCargo
	}
	return false
}

func (x *Metadados_CSV) GetDetalhamentoReceitaBase() Metadados_CSV_OpcoesDetalhamento {
	if x != nil {
		return x.DetalhamentoReceitaBase
	}
	return Metadados_CSV_AUSENCIA
}

func (x *Metadados_CSV) GetDetalhamentoOutrasReceitas() Metadados_CSV_OpcoesDetalhamento {
	if x != nil {
		return x.DetalhamentoOutrasReceitas
	}
	return Metadados_CSV_AUSENCIA
}

func (x *Metadados_CSV) GetDetalhamentoDescontos() Metadados_CSV_OpcoesDetalhamento {
	if x != nil {
		return x.DetalhamentoDescontos
	}
	return Metadados_CSV_AUSENCIA
}

var File_pacote_proto protoreflect.FileDescriptor

var file_pacote_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xcc, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x43, 0x6f, 0x6c,
	0x65, 0x74, 0x61, 0x5f, 0x43, 0x53, 0x56, 0x12, 0x23, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x65, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x6f, 0x6c, 0x65, 0x74, 0x61,
	0x5f, 0x43, 0x53, 0x56, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x65, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x0c,
	0x72, 0x65, 0x6d, 0x75, 0x6e, 0x65, 0x72, 0x61, 0x63, 0x6f, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x52, 0x65, 0x6d, 0x75, 0x6e, 0x65, 0x72, 0x61, 0x63, 0x6f, 0x65,
	0x73, 0x5f, 0x43, 0x53, 0x56, 0x52, 0x0c, 0x72, 0x65, 0x6d, 0x75, 0x6e, 0x65, 0x72, 0x61, 0x63,
	0x6f, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x05, 0x66, 0x6f, 0x6c, 0x68, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x46, 0x6f, 0x6c, 0x68, 0x61, 0x44, 0x65, 0x50, 0x61, 0x67, 0x61,
	0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x5f, 0x43, 0x53, 0x56, 0x52, 0x05, 0x66, 0x6f, 0x6c, 0x68, 0x61,
	0x12, 0x2c, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x5f,
	0x43, 0x53, 0x56, 0x52, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x22, 0xa9,
	0x02, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x65, 0x74, 0x61, 0x5f, 0x43, 0x53, 0x56, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x68, 0x61, 0x76, 0x65, 0x5f, 0x63, 0x6f, 0x6c, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x76, 0x65, 0x43, 0x6f, 0x6c, 0x65, 0x74, 0x61,
	0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x67, 0x61, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6f, 0x72, 0x67, 0x61, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x6e, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x6e, 0x6f, 0x12, 0x45, 0x0a, 0x10, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x63, 0x6f, 0x6c, 0x65, 0x74, 0x61, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x43, 0x6f, 0x6c, 0x65, 0x74,
	0x61, 0x12, 0x2f, 0x0a, 0x13, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6f,
	0x5f, 0x63, 0x6f, 0x6c, 0x65, 0x74, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12,
	0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6f, 0x43, 0x6f, 0x6c, 0x65, 0x74,
	0x6f, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6f, 0x5f, 0x63, 0x6f, 0x6c,
	0x65, 0x74, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x76, 0x65, 0x72, 0x73,
	0x61, 0x6f, 0x43, 0x6f, 0x6c, 0x65, 0x74, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x72,
	0x5f, 0x63, 0x6f, 0x6c, 0x65, 0x74, 0x6f, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x64, 0x69, 0x72, 0x43, 0x6f, 0x6c, 0x65, 0x74, 0x6f, 0x72, 0x22, 0x4e, 0x0a, 0x14, 0x46, 0x6f,
	0x6c, 0x68, 0x61, 0x44, 0x65, 0x50, 0x61, 0x67, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x5f, 0x43,
	0x53, 0x56, 0x12, 0x36, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x5f, 0x63, 0x68, 0x65,
	0x71, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x43, 0x68, 0x65, 0x71, 0x75, 0x65, 0x5f, 0x43, 0x53, 0x56, 0x52, 0x0c, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x43, 0x68, 0x65, 0x71, 0x75, 0x65, 0x22, 0xb4, 0x02, 0x0a, 0x10, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x43, 0x68, 0x65, 0x71, 0x75, 0x65, 0x5f, 0x43, 0x53, 0x56, 0x12,
	0x28, 0x0a, 0x10, 0x69, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x5f, 0x63, 0x68, 0x65,
	0x71, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x64, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x43, 0x68, 0x65, 0x71, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61,
	0x76, 0x65, 0x5f, 0x63, 0x6f, 0x6c, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x68, 0x61, 0x76, 0x65, 0x43, 0x6f, 0x6c, 0x65, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x63, 0x75, 0x6c, 0x61, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x63, 0x75, 0x6c, 0x61, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x75, 0x6e, 0x63, 0x61, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x66, 0x75, 0x6e, 0x63, 0x61, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f,
	0x74, 0x72, 0x61, 0x62, 0x61, 0x6c, 0x68, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x62, 0x61, 0x6c, 0x68, 0x6f, 0x12, 0x2a, 0x0a,
	0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x43, 0x68, 0x65, 0x71, 0x75, 0x65, 0x5f, 0x43, 0x53, 0x56, 0x2e, 0x54,
	0x69, 0x70, 0x6f, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x74, 0x69,
	0x76, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x74, 0x69, 0x76, 0x6f, 0x22,
	0x20, 0x0a, 0x04, 0x54, 0x69, 0x70, 0x6f, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45, 0x4d, 0x42, 0x52,
	0x4f, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x45, 0x52, 0x56, 0x49, 0x44, 0x4f, 0x52, 0x10,
	0x01, 0x22, 0x46, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x75, 0x6e, 0x65, 0x72, 0x61, 0x63, 0x6f, 0x65,
	0x73, 0x5f, 0x43, 0x53, 0x56, 0x12, 0x32, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x75, 0x6e, 0x65, 0x72,
	0x61, 0x63, 0x61, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x52, 0x65, 0x6d,
	0x75, 0x6e, 0x65, 0x72, 0x61, 0x63, 0x61, 0x6f, 0x5f, 0x43, 0x53, 0x56, 0x52, 0x0b, 0x72, 0x65,
	0x6d, 0x75, 0x6e, 0x65, 0x72, 0x61, 0x63, 0x61, 0x6f, 0x22, 0xf7, 0x01, 0x0a, 0x0f, 0x52, 0x65,
	0x6d, 0x75, 0x6e, 0x65, 0x72, 0x61, 0x63, 0x61, 0x6f, 0x5f, 0x43, 0x53, 0x56, 0x12, 0x28, 0x0a,
	0x10, 0x69, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x5f, 0x63, 0x68, 0x65, 0x71, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x43, 0x68, 0x65, 0x71, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x76, 0x65,
	0x5f, 0x63, 0x6f, 0x6c, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x68, 0x61, 0x76, 0x65, 0x43, 0x6f, 0x6c, 0x65, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x08, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x7a, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x52,
	0x65, 0x6d, 0x75, 0x6e, 0x65, 0x72, 0x61, 0x63, 0x61, 0x6f, 0x5f, 0x43, 0x53, 0x56, 0x2e, 0x4e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x7a, 0x61, 0x52, 0x08, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x7a,
	0x61, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69,
	0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x22, 0x18, 0x0a, 0x08, 0x4e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x7a, 0x61, 0x12, 0x05, 0x0a, 0x01, 0x52, 0x10, 0x00, 0x12, 0x05, 0x0a, 0x01,
	0x44, 0x10, 0x01, 0x22, 0xaf, 0x07, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x64, 0x6f,
	0x73, 0x5f, 0x43, 0x53, 0x56, 0x12, 0x28, 0x0a, 0x10, 0x6e, 0x61, 0x6f, 0x5f, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0e, 0x6e, 0x61, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x2c, 0x0a, 0x12, 0x6e, 0x61, 0x6f, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x72, 0x5f, 0x63, 0x61,
	0x70, 0x74, 0x63, 0x68, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x6e, 0x61, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x72, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x12, 0x34, 0x0a,
	0x06, 0x61, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x5f, 0x43, 0x53, 0x56, 0x2e, 0x46, 0x6f,
	0x72, 0x6d, 0x61, 0x44, 0x65, 0x41, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x06, 0x61, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x12, 0x33, 0x0a, 0x08, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x61, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x64, 0x6f,
	0x73, 0x5f, 0x43, 0x53, 0x56, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x61, 0x6f, 0x52, 0x08,
	0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x61, 0x6f, 0x12, 0x31, 0x0a, 0x14, 0x65, 0x73, 0x74, 0x72,
	0x69, 0x74, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x5f, 0x74, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x65, 0x73, 0x74, 0x72, 0x69, 0x74, 0x61, 0x6d,
	0x65, 0x6e, 0x74, 0x65, 0x54, 0x61, 0x62, 0x75, 0x6c, 0x61, 0x72, 0x12, 0x2f, 0x0a, 0x13, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x6f, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x74, 0x65, 0x6d, 0x5f, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x63, 0x75, 0x6c, 0x61, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x63, 0x75, 0x6c,
	0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x5f, 0x6c, 0x6f, 0x74, 0x61, 0x63, 0x61, 0x6f,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x4c, 0x6f, 0x74, 0x61, 0x63,
	0x61, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6d, 0x5f, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x12,
	0x5d, 0x0a, 0x19, 0x64, 0x65, 0x74, 0x61, 0x6c, 0x68, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x5f,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x74, 0x61, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x21, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x5f, 0x43,
	0x53, 0x56, 0x2e, 0x4f, 0x70, 0x63, 0x6f, 0x65, 0x73, 0x44, 0x65, 0x74, 0x61, 0x6c, 0x68, 0x61,
	0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x52, 0x17, 0x64, 0x65, 0x74, 0x61, 0x6c, 0x68, 0x61, 0x6d, 0x65,
	0x6e, 0x74, 0x6f, 0x52, 0x65, 0x63, 0x65, 0x69, 0x74, 0x61, 0x42, 0x61, 0x73, 0x65, 0x12, 0x63,
	0x0a, 0x1c, 0x64, 0x65, 0x74, 0x61, 0x6c, 0x68, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x5f, 0x6f,
	0x75, 0x74, 0x72, 0x61, 0x73, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x74, 0x61, 0x73, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x64, 0x6f, 0x73,
	0x5f, 0x43, 0x53, 0x56, 0x2e, 0x4f, 0x70, 0x63, 0x6f, 0x65, 0x73, 0x44, 0x65, 0x74, 0x61, 0x6c,
	0x68, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x52, 0x1a, 0x64, 0x65, 0x74, 0x61, 0x6c, 0x68, 0x61,
	0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x4f, 0x75, 0x74, 0x72, 0x61, 0x73, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x74, 0x61, 0x73, 0x12, 0x58, 0x0a, 0x16, 0x64, 0x65, 0x74, 0x61, 0x6c, 0x68, 0x61, 0x6d, 0x65,
	0x6e, 0x74, 0x6f, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x6f, 0x6e, 0x74, 0x6f, 0x73, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x5f,
	0x43, 0x53, 0x56, 0x2e, 0x4f, 0x70, 0x63, 0x6f, 0x65, 0x73, 0x44, 0x65, 0x74, 0x61, 0x6c, 0x68,
	0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x52, 0x15, 0x64, 0x65, 0x74, 0x61, 0x6c, 0x68, 0x61, 0x6d,
	0x65, 0x6e, 0x74, 0x6f, 0x44, 0x65, 0x73, 0x63, 0x6f, 0x6e, 0x74, 0x6f, 0x73, 0x22, 0x79, 0x0a,
	0x0d, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x44, 0x65, 0x41, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x12, 0x11,
	0x0a, 0x0d, 0x41, 0x43, 0x45, 0x53, 0x53, 0x4f, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x54, 0x4f, 0x10,
	0x00, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x4d, 0x49, 0x47, 0x41, 0x56, 0x45, 0x4c, 0x5f, 0x50, 0x41,
	0x52, 0x41, 0x5f, 0x52, 0x41, 0x53, 0x50, 0x41, 0x47, 0x45, 0x4d, 0x10, 0x01, 0x12, 0x18, 0x0a,
	0x14, 0x52, 0x41, 0x53, 0x50, 0x41, 0x47, 0x45, 0x4d, 0x5f, 0x44, 0x49, 0x46, 0x49, 0x43, 0x55,
	0x4c, 0x54, 0x41, 0x44, 0x41, 0x10, 0x02, 0x12, 0x1f, 0x0a, 0x1b, 0x4e, 0x45, 0x43, 0x45, 0x53,
	0x53, 0x49, 0x54, 0x41, 0x5f, 0x53, 0x49, 0x4d, 0x55, 0x4c, 0x41, 0x43, 0x41, 0x4f, 0x5f, 0x55,
	0x53, 0x55, 0x41, 0x52, 0x49, 0x4f, 0x10, 0x03, 0x22, 0x38, 0x0a, 0x08, 0x45, 0x78, 0x74, 0x65,
	0x6e, 0x73, 0x61, 0x6f, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x44, 0x46, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x4f, 0x44, 0x53, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x58, 0x4c, 0x53, 0x10, 0x02, 0x12,
	0x08, 0x0a, 0x04, 0x4a, 0x53, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x53, 0x56,
	0x10, 0x04, 0x22, 0x41, 0x0a, 0x12, 0x4f, 0x70, 0x63, 0x6f, 0x65, 0x73, 0x44, 0x65, 0x74, 0x61,
	0x6c, 0x68, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x55, 0x53, 0x45,
	0x4e, 0x43, 0x49, 0x41, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x55, 0x4d, 0x41, 0x52, 0x49,
	0x5a, 0x41, 0x44, 0x4f, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x45, 0x54, 0x41, 0x4c, 0x48,
	0x41, 0x44, 0x4f, 0x10, 0x02, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x6a, 0x75, 0x73, 0x62, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x73, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pacote_proto_rawDescOnce sync.Once
	file_pacote_proto_rawDescData = file_pacote_proto_rawDesc
)

func file_pacote_proto_rawDescGZIP() []byte {
	file_pacote_proto_rawDescOnce.Do(func() {
		file_pacote_proto_rawDescData = protoimpl.X.CompressGZIP(file_pacote_proto_rawDescData)
	})
	return file_pacote_proto_rawDescData
}

var file_pacote_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_pacote_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pacote_proto_goTypes = []interface{}{
	(ContraCheque_CSV_Tipo)(0),            // 0: ContraCheque_CSV.Tipo
	(Remuneracao_CSV_Natureza)(0),         // 1: Remuneracao_CSV.Natureza
	(Metadados_CSV_FormaDeAcesso)(0),      // 2: Metadados_CSV.FormaDeAcesso
	(Metadados_CSV_Extensao)(0),           // 3: Metadados_CSV.Extensao
	(Metadados_CSV_OpcoesDetalhamento)(0), // 4: Metadados_CSV.OpcoesDetalhamento
	(*ResultadoColeta_CSV)(nil),           // 5: ResultadoColeta_CSV
	(*Coleta_CSV)(nil),                    // 6: Coleta_CSV
	(*FolhaDePagamento_CSV)(nil),          // 7: FolhaDePagamento_CSV
	(*ContraCheque_CSV)(nil),              // 8: ContraCheque_CSV
	(*Remuneracoes_CSV)(nil),              // 9: Remuneracoes_CSV
	(*Remuneracao_CSV)(nil),               // 10: Remuneracao_CSV
	(*Metadados_CSV)(nil),                 // 11: Metadados_CSV
	(*timestamp.Timestamp)(nil),           // 12: google.protobuf.Timestamp
}
var file_pacote_proto_depIdxs = []int32{
	6,  // 0: ResultadoColeta_CSV.coleta:type_name -> Coleta_CSV
	9,  // 1: ResultadoColeta_CSV.remuneracoes:type_name -> Remuneracoes_CSV
	7,  // 2: ResultadoColeta_CSV.folha:type_name -> FolhaDePagamento_CSV
	11, // 3: ResultadoColeta_CSV.metadados:type_name -> Metadados_CSV
	12, // 4: Coleta_CSV.timestamp_coleta:type_name -> google.protobuf.Timestamp
	8,  // 5: FolhaDePagamento_CSV.contra_cheque:type_name -> ContraCheque_CSV
	0,  // 6: ContraCheque_CSV.tipo:type_name -> ContraCheque_CSV.Tipo
	10, // 7: Remuneracoes_CSV.remuneracao:type_name -> Remuneracao_CSV
	1,  // 8: Remuneracao_CSV.natureza:type_name -> Remuneracao_CSV.Natureza
	2,  // 9: Metadados_CSV.acesso:type_name -> Metadados_CSV.FormaDeAcesso
	3,  // 10: Metadados_CSV.extensao:type_name -> Metadados_CSV.Extensao
	4,  // 11: Metadados_CSV.detalhamento_receita_base:type_name -> Metadados_CSV.OpcoesDetalhamento
	4,  // 12: Metadados_CSV.detalhamento_outras_receitas:type_name -> Metadados_CSV.OpcoesDetalhamento
	4,  // 13: Metadados_CSV.detalhamento_descontos:type_name -> Metadados_CSV.OpcoesDetalhamento
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_pacote_proto_init() }
func file_pacote_proto_init() {
	if File_pacote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pacote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultadoColeta_CSV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pacote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coleta_CSV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pacote_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FolhaDePagamento_CSV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pacote_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContraCheque_CSV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pacote_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Remuneracoes_CSV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pacote_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Remuneracao_CSV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pacote_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadados_CSV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pacote_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pacote_proto_goTypes,
		DependencyIndexes: file_pacote_proto_depIdxs,
		EnumInfos:         file_pacote_proto_enumTypes,
		MessageInfos:      file_pacote_proto_msgTypes,
	}.Build()
	File_pacote_proto = out.File
	file_pacote_proto_rawDesc = nil
	file_pacote_proto_goTypes = nil
	file_pacote_proto_depIdxs = nil
}
