// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: pipeline.proto

package pipeline

import (
	coleta "github.com/dadosjusbr/proto/coleta"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResultadoExecucao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pr *ResultadoEmpacotamento `protobuf:"bytes,1,opt,name=pr,proto3" json:"pr,omitempty"`
	Rc *coleta.ResultadoColeta `protobuf:"bytes,2,opt,name=rc,proto3" json:"rc,omitempty"`
}

func (x *ResultadoExecucao) Reset() {
	*x = ResultadoExecucao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pipeline_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultadoExecucao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoExecucao) ProtoMessage() {}

func (x *ResultadoExecucao) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoExecucao.ProtoReflect.Descriptor instead.
func (*ResultadoExecucao) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{0}
}

func (x *ResultadoExecucao) GetPr() *ResultadoEmpacotamento {
	if x != nil {
		return x.Pr
	}
	return nil
}

func (x *ResultadoExecucao) GetRc() *coleta.ResultadoColeta {
	if x != nil {
		return x.Rc
	}
	return nil
}

// PackagingResult holds the result of the package step, which creates the datapackage.
type ResultadoEmpacotamento struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pacote       string           `protobuf:"bytes,1,opt,name=pacote,proto3" json:"pacote,omitempty"`
	Procinfo     *coleta.ProcInfo `protobuf:"bytes,2,opt,name=procinfo,proto3" json:"procinfo,omitempty"`
	Remuneracoes string           `protobuf:"bytes,3,opt,name=remuneracoes,proto3" json:"remuneracoes,omitempty"`
}

func (x *ResultadoEmpacotamento) Reset() {
	*x = ResultadoEmpacotamento{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pipeline_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultadoEmpacotamento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoEmpacotamento) ProtoMessage() {}

func (x *ResultadoEmpacotamento) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoEmpacotamento.ProtoReflect.Descriptor instead.
func (*ResultadoEmpacotamento) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{1}
}

func (x *ResultadoEmpacotamento) GetPacote() string {
	if x != nil {
		return x.Pacote
	}
	return ""
}

func (x *ResultadoEmpacotamento) GetProcinfo() *coleta.ProcInfo {
	if x != nil {
		return x.Procinfo
	}
	return nil
}

func (x *ResultadoEmpacotamento) GetRemuneracoes() string {
	if x != nil {
		return x.Remuneracoes
	}
	return ""
}

var File_pipeline_proto protoreflect.FileDescriptor

var file_pipeline_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0c, 0x63, 0x6f, 0x6c, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5e,
	0x0a, 0x11, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x63, 0x61, 0x6f, 0x12, 0x27, 0x0a, 0x02, 0x70, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x45, 0x6d, 0x70, 0x61, 0x63,
	0x6f, 0x74, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x52, 0x02, 0x70, 0x72, 0x12, 0x20, 0x0a, 0x02,
	0x72, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x61, 0x64, 0x6f, 0x43, 0x6f, 0x6c, 0x65, 0x74, 0x61, 0x52, 0x02, 0x72, 0x63, 0x22, 0x7b,
	0x0a, 0x16, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x45, 0x6d, 0x70, 0x61, 0x63,
	0x6f, 0x74, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x63, 0x6f,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x63, 0x6f, 0x74, 0x65,
	0x12, 0x25, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x63, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x63, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x6d, 0x75, 0x6e,
	0x65, 0x72, 0x61, 0x63, 0x6f, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72,
	0x65, 0x6d, 0x75, 0x6e, 0x65, 0x72, 0x61, 0x63, 0x6f, 0x65, 0x73, 0x42, 0x26, 0x5a, 0x24, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x6a,
	0x75, 0x73, 0x62, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pipeline_proto_rawDescOnce sync.Once
	file_pipeline_proto_rawDescData = file_pipeline_proto_rawDesc
)

func file_pipeline_proto_rawDescGZIP() []byte {
	file_pipeline_proto_rawDescOnce.Do(func() {
		file_pipeline_proto_rawDescData = protoimpl.X.CompressGZIP(file_pipeline_proto_rawDescData)
	})
	return file_pipeline_proto_rawDescData
}

var file_pipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pipeline_proto_goTypes = []interface{}{
	(*ResultadoExecucao)(nil),      // 0: ResultadoExecucao
	(*ResultadoEmpacotamento)(nil), // 1: ResultadoEmpacotamento
	(*coleta.ResultadoColeta)(nil), // 2: ResultadoColeta
	(*coleta.ProcInfo)(nil),        // 3: ProcInfo
}
var file_pipeline_proto_depIdxs = []int32{
	1, // 0: ResultadoExecucao.pr:type_name -> ResultadoEmpacotamento
	2, // 1: ResultadoExecucao.rc:type_name -> ResultadoColeta
	3, // 2: ResultadoEmpacotamento.procinfo:type_name -> ProcInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pipeline_proto_init() }
func file_pipeline_proto_init() {
	if File_pipeline_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pipeline_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultadoExecucao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pipeline_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultadoEmpacotamento); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pipeline_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pipeline_proto_goTypes,
		DependencyIndexes: file_pipeline_proto_depIdxs,
		MessageInfos:      file_pipeline_proto_msgTypes,
	}.Build()
	File_pipeline_proto = out.File
	file_pipeline_proto_rawDesc = nil
	file_pipeline_proto_goTypes = nil
	file_pipeline_proto_depIdxs = nil
}
