// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pipeline.proto

package pipeline

import (
	fmt "fmt"
	coleta "github.com/dadosjusbr/proto/coleta"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResultadoExecucao struct {
	Pr                   *ResultadoEmpacotamento `protobuf:"bytes,1,opt,name=pr,proto3" json:"pr,omitempty"`
	Rc                   *coleta.ResultadoColeta `protobuf:"bytes,2,opt,name=rc,proto3" json:"rc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ResultadoExecucao) Reset()         { *m = ResultadoExecucao{} }
func (m *ResultadoExecucao) String() string { return proto.CompactTextString(m) }
func (*ResultadoExecucao) ProtoMessage()    {}
func (*ResultadoExecucao) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{0}
}

func (m *ResultadoExecucao) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultadoExecucao.Unmarshal(m, b)
}
func (m *ResultadoExecucao) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultadoExecucao.Marshal(b, m, deterministic)
}
func (m *ResultadoExecucao) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultadoExecucao.Merge(m, src)
}
func (m *ResultadoExecucao) XXX_Size() int {
	return xxx_messageInfo_ResultadoExecucao.Size(m)
}
func (m *ResultadoExecucao) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultadoExecucao.DiscardUnknown(m)
}

var xxx_messageInfo_ResultadoExecucao proto.InternalMessageInfo

func (m *ResultadoExecucao) GetPr() *ResultadoEmpacotamento {
	if m != nil {
		return m.Pr
	}
	return nil
}

func (m *ResultadoExecucao) GetRc() *coleta.ResultadoColeta {
	if m != nil {
		return m.Rc
	}
	return nil
}

// PackagingResult holds the result of the package step, which creates the datapackage.
type ResultadoEmpacotamento struct {
	//Caminho completo para o zip do datapackage na máquina
	Pacote string `protobuf:"bytes,1,opt,name=pacote,proto3" json:"pacote,omitempty"`
	//Estrutura que contém as informacões do processo da coleta caso tenha dado erro
	Procinfo *coleta.ProcInfo `protobuf:"bytes,2,opt,name=procinfo,proto3" json:"procinfo,omitempty"`
	//Caminho completo para o zip das remuneracões na máquina
	Remuneracoes         string   `protobuf:"bytes,3,opt,name=remuneracoes,proto3" json:"remuneracoes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultadoEmpacotamento) Reset()         { *m = ResultadoEmpacotamento{} }
func (m *ResultadoEmpacotamento) String() string { return proto.CompactTextString(m) }
func (*ResultadoEmpacotamento) ProtoMessage()    {}
func (*ResultadoEmpacotamento) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac67a7adf3df9c7, []int{1}
}

func (m *ResultadoEmpacotamento) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultadoEmpacotamento.Unmarshal(m, b)
}
func (m *ResultadoEmpacotamento) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultadoEmpacotamento.Marshal(b, m, deterministic)
}
func (m *ResultadoEmpacotamento) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultadoEmpacotamento.Merge(m, src)
}
func (m *ResultadoEmpacotamento) XXX_Size() int {
	return xxx_messageInfo_ResultadoEmpacotamento.Size(m)
}
func (m *ResultadoEmpacotamento) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultadoEmpacotamento.DiscardUnknown(m)
}

var xxx_messageInfo_ResultadoEmpacotamento proto.InternalMessageInfo

func (m *ResultadoEmpacotamento) GetPacote() string {
	if m != nil {
		return m.Pacote
	}
	return ""
}

func (m *ResultadoEmpacotamento) GetProcinfo() *coleta.ProcInfo {
	if m != nil {
		return m.Procinfo
	}
	return nil
}

func (m *ResultadoEmpacotamento) GetRemuneracoes() string {
	if m != nil {
		return m.Remuneracoes
	}
	return ""
}

func init() {
	proto.RegisterType((*ResultadoExecucao)(nil), "ResultadoExecucao")
	proto.RegisterType((*ResultadoEmpacotamento)(nil), "ResultadoEmpacotamento")
}

func init() { proto.RegisterFile("pipeline.proto", fileDescriptor_7ac67a7adf3df9c7) }

var fileDescriptor_7ac67a7adf3df9c7 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x69, 0x84, 0x62, 0xc7, 0x22, 0x9a, 0x43, 0x5d, 0x3c, 0x95, 0xc5, 0x7f, 0xa7, 0x5d,
	0xd0, 0x6f, 0xa0, 0x78, 0xf0, 0x26, 0x39, 0x7a, 0x10, 0xb2, 0xb3, 0x53, 0x8d, 0x6c, 0x32, 0x61,
	0x92, 0x80, 0xe0, 0x97, 0x17, 0x62, 0xb5, 0x08, 0x3d, 0xfe, 0xe6, 0xbd, 0x79, 0x8f, 0x19, 0x38,
	0x8e, 0x2e, 0xd2, 0xe4, 0x02, 0x75, 0x51, 0x38, 0xf3, 0xf9, 0x12, 0x79, 0xa2, 0x6c, 0x7f, 0xa8,
	0x7d, 0x85, 0x53, 0x43, 0xa9, 0x4c, 0xd9, 0x8e, 0xfc, 0xf8, 0x49, 0x58, 0xd0, 0xb2, 0xbe, 0x06,
	0x15, 0xa5, 0x99, 0xad, 0x67, 0x37, 0x47, 0xb7, 0x67, 0xdd, 0x4e, 0xf7, 0xd1, 0x22, 0x67, 0xeb,
	0x29, 0x64, 0x36, 0x2a, 0x8a, 0x5e, 0x83, 0x12, 0x6c, 0x54, 0x35, 0x9e, 0xec, 0x8c, 0x0f, 0xb5,
	0xc1, 0x28, 0xc1, 0xf6, 0x0b, 0x56, 0xfb, 0xf7, 0xf5, 0x0a, 0xe6, 0x15, 0xa9, 0x16, 0x2d, 0xcc,
	0x96, 0xf4, 0x25, 0x1c, 0x46, 0x61, 0x74, 0x61, 0xc3, 0xdb, 0xe4, 0x45, 0xf7, 0x2c, 0x8c, 0x4f,
	0x61, 0xc3, 0xe6, 0x4f, 0xd2, 0x2d, 0x2c, 0x85, 0x7c, 0x09, 0x24, 0x16, 0x99, 0x52, 0x73, 0x50,
	0x43, 0xfe, 0xcd, 0xee, 0xaf, 0x5e, 0x2e, 0xde, 0x5c, 0x7e, 0x2f, 0x43, 0x87, 0xec, 0xfb, 0xd1,
	0x8e, 0x9c, 0x3e, 0x4a, 0x1a, 0xa4, 0xaf, 0xb7, 0xf7, 0xbf, 0x8f, 0x19, 0xe6, 0x95, 0xef, 0xbe,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x6c, 0x4b, 0xf4, 0x2b, 0x01, 0x00, 0x00,
}
